# Generated by Django 2.1.4 on 2018-12-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neijing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeiJingBlank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('blank_index', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'NeiJingBlank',
                'verbose_name_plural': 'NeiJingBlanks',
            },
        ),
        migrations.AlterField(
            model_name='neijingraw',
            name='blank',
            field=models.IntegerField(default=10, verbose_name='设置几个填空'),
        ),
        migrations.AddField(
            model_name='neijingblank',
            name='raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neijing.NeiJingRaw'),
        ),
    ]
