# Generated by Django 2.1.4 on 2018-12-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neijing', '0002_auto_20181216_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeiJingBlank',
            new_name='NeiJingParaGraph',
        ),
        migrations.AlterModelOptions(
            name='neijingparagraph',
            options={'verbose_name': 'NeiJingParaGraph', 'verbose_name_plural': 'NeiJingParaGraph'},
        ),
    ]
