# Generated by Django 2.1.4 on 2018-12-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neijing', '0003_auto_20181216_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neijingparagraph',
            name='raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='neijing.NeiJingRaw'),
        ),
    ]
