# Generated by Django 2.1.4 on 2018-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neijing', '0004_auto_20181216_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neijingparagraph',
            options={'verbose_name': '段落', 'verbose_name_plural': '段落'},
        ),
        migrations.AlterField(
            model_name='neijingparagraph',
            name='blank_index',
            field=models.CharField(default='', max_length=255),
        ),
    ]
