# Generated by Django 2.1.4 on 2018-12-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neijing', '0005_auto_20181216_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeiJingExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('answers', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='neijingraw',
            old_name='blank',
            new_name='blank_count',
        ),
        migrations.AddField(
            model_name='neijingexam',
            name='exam_raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neijing.NeiJingRaw'),
        ),
    ]
