# Generated by Django 2.1.4 on 2018-12-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neijing', '0006_auto_20181216_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neijingexam',
            name='answers',
        ),
        migrations.AddField(
            model_name='neijingexam',
            name='blanks',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='neijingexam',
            name='right_answers',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='neijingexam',
            name='u_answers',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='neijingparagraph',
            name='content',
            field=models.TextField(help_text='点击标记或取消标记，红色为填空内容', verbose_name='内容'),
        ),
    ]
