# Generated by Django 2.1.2 on 2018-12-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neijing', '0007_auto_20181216_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neijingexam',
            name='right_answers',
        ),
        migrations.AddField(
            model_name='neijingexam',
            name='right_answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
