# Generated by Django 2.1.2 on 2018-12-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('neijing', '0008_auto_20181216_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='neijingexam',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
