# Generated by Django 2.2.2 on 2019-06-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neijing', '0010_auto_20190303_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neijingexam',
            options={'ordering': ['-id'], 'verbose_name': '测试', 'verbose_name_plural': '测试'},
        ),
        migrations.AlterModelOptions(
            name='neijingraw',
            options={'verbose_name': '内经原文', 'verbose_name_plural': '内经原文'},
        ),
    ]
