version: '2.1'

services:
  redis_db:
    image: redis
    container_name: medicine_redis
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - "3306"
    volumes:
      - redis-data:/data
    networks:
      - medicine_network

  web:
    container_name: medicine_web
    image: medicine
    networks:
      - medicine_network
    volumes:
      - .:/app
      - django-static:/app/static
    build: .
    depends_on:
      - redis_db
    
  nginx:
    image: nginx
    restart: always
    container_name: medicine_nginx
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d
      - django-static:/app/static
    ports:
      - 8002:80
    networks:
      - medicine_network
    depends_on:
      - web


networks:
  medicine_network:

volumes:
  redis-data:
  django-static:
    