# Generated by Django 2.2.2 on 2019-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181207_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunbo',
            name='vurl',
            field=models.URLField(blank=True, null=True, verbose_name='视频地址'),
        ),
    ]
