# Generated by Django 2.1.2 on 2018-10-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0002_auto_20181005_1547'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('from_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_from', to='user.User')),
                ('to_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to', to='user.User')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.Disease')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
