# Generated by Django 2.1.2 on 2018-10-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='from_u',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='to_u',
            new_name='to_user',
        ),
    ]
