# Generated by Django 2.1.2 on 2018-12-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20181006_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_time'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
