# Generated by Django 2.1.1 on 2018-09-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': '疾病', 'verbose_name_plural': '疾病'},
        ),
        migrations.AddField(
            model_name='diseasetype',
            name='type_symptoms',
            field=models.CharField(default=0, max_length=200, verbose_name='分型症状'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='main_prescription',
            field=models.ManyToManyField(blank=True, to='disease.MainPrescription', verbose_name='主药方'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='main_symptoms',
            field=models.ManyToManyField(to='disease.MainSymptoms', verbose_name='主要症状'),
        ),
    ]
