# Generated by Django 2.1.1 on 2018-09-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_user', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('case_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.Disease')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='CaseSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.Case')),
                ('symptoms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disease.Symptoms')),
            ],
            options={
                'verbose_name': 'CaseSymptoms',
                'verbose_name_plural': 'CaseSymptomss',
            },
        ),
        migrations.RenameModel(
            old_name='DiseaseType',
            new_name='DiseaseTyping',
        ),
        migrations.AlterUniqueTogether(
            name='casesymptoms',
            unique_together={('case', 'symptoms')},
        ),
    ]
