# Generated by Django 2.1.1 on 2018-09-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20180918_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTyping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.Case')),
                ('typing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disease.DiseaseTyping')),
            ],
            options={
                'verbose_name': 'CaseTyping',
                'verbose_name_plural': 'CaseTypings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='casesymptoms',
            unique_together=set(),
        ),
    ]
