# Generated by Django 2.1.1 on 2018-09-16 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20180916_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasetype',
            name='add_prescription',
            field=models.ManyToManyField(to='disease.MainPrescription', verbose_name='处方加减'),
        ),
        migrations.AlterField(
            model_name='diseasetype',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.Disease', verbose_name='疾病'),
        ),
    ]
