# Generated by Django 2.1.1 on 2018-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_auto_20180918_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
