# Generated by Django 2.1.2 on 2018-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_auto_20181006_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasetyping',
            name='typing_symptoms',
            field=models.ManyToManyField(blank=True, help_text='test', to='disease.DiseaseTypingSymptoms', verbose_name='分型症状'),
        ),
    ]
