# Generated by Django 2.1.2 on 2018-10-06 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('disease', '0005_auto_20181006_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.Disease')),
                ('fa_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': 'FavList',
                'verbose_name_plural': 'FavList',
            },
        ),
    ]
