# Generated by Django 2.1.1 on 2018-09-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_auto_20180918_1818'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casetyping',
            unique_together={('case', 'typing')},
        ),
    ]
