# Generated by Django 2.1.1 on 2018-09-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0006_auto_20180919_2003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casesymptoms',
            unique_together={('case', 'symptoms')},
        ),
    ]
