# Generated by Django 2.1.2 on 2018-12-07 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0009_auto_20181007_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favlist',
            name='fa_case',
        ),
        migrations.AddField(
            model_name='favlist',
            name='fa_disease',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disease.Disease'),
            preserve_default=False,
        ),
    ]
