# Generated by Django 2.1.2 on 2018-12-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0010_auto_20181207_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='tips',
            field=models.TextField(blank=True, null=True, verbose_name='小提示'),
        ),
    ]
