# Generated by Django 2.1.4 on 2018-12-08 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0012_auto_20181207_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptoms',
            options={'ordering': ['-count'], 'verbose_name': '主症', 'verbose_name_plural': '主症'},
        ),
        migrations.AddField(
            model_name='symptoms',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disease',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disease.Category', verbose_name='分类'),
        ),
    ]
