# Generated by Django 2.1.2 on 2018-12-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0013_auto_20181208_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptoms',
            options={'verbose_name': '主症', 'verbose_name_plural': '主症'},
        ),
    ]
