# Generated by Django 2.2.2 on 2019-06-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0014_auto_20181217_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '案例', 'verbose_name_plural': '案例s'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
