# Generated by Django 2.2.2 on 2019-06-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0015_auto_20190612_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '案例', 'verbose_name_plural': '案例'},
        ),
    ]
